apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: insurratex

bases:
- ../../base

commonLabels:
  environment: production

patches:
- target:
    kind: Deployment
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 512Mi
    - op: add
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 1Gi

images:
- name: insurratex/orchestrator
  newTag: latest
- name: insurratex/guidewire-mock
  newTag: latest
- name: insurratex/earnix-mock
  newTag: latest
- name: insurratex/mapping-ui
  newTag: latest
- name: insurratex/rules-ui
  newTag: latest
