apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: insurratex

resources:
- namespace.yaml
- orchestrator-deployment.yaml
- guidewire-deployment.yaml
- earnix-deployment.yaml
- mapping-ui-deployment.yaml
- rules-ui-deployment.yaml
- ingress.yaml
- hpa.yaml

commonLabels:
  platform: insurratex
  managed-by: kustomize
