apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: insurratex-dev

bases:
- ../../base

namePrefix: dev-

commonLabels:
  environment: development

patches:
- target:
    kind: Deployment
    name: orchestrator
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: development

- target:
    kind: HorizontalPodAutoscaler
    name: orchestrator-hpa
  patch: |-
    - op: replace
      path: /spec/minReplicas
      value: 1
    - op: replace
      path: /spec/maxReplicas
      value: 3

images:
- name: insurratex/orchestrator
  newTag: develop
- name: insurratex/guidewire-mock
  newTag: develop
- name: insurratex/earnix-mock
  newTag: develop
- name: insurratex/mapping-ui
  newTag: develop
- name: insurratex/rules-ui
  newTag: develop
